#!/bin/bash
set -e

docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL=`git config --get remote.origin.url` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg PARENT_DOCKER=mro-verse
  -f $DOCKERFILE_PATH 
  -t $IMAGE_NAME .
