name: base
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python=3.6.7
  - notebook=6.1.5
  - jupyterhub=1.2.2
  - jupyterlab=2.2.9
  - awscli=1.18.121
  - boto3=1.14.44
  - botocore=1.17.44
  - dask=2.26.0
  - dask-core=2.26.0
  - numpy=1.16.5
  - pandas=1.0.1
  - scikit-learn=0.21.2
  - matplotlib-base=3.1.2
  - matplotlib=3.1.2
  - pyyaml=3.13
  - h5py=2.9.0
  - pytorch=1.6.0
  - pip=19.2.1
  - tini=0.18.0
  - plotly
  - cython
  - nomkl
