name: base
channels:
  - conda-forge
  - pytorch
  - bioconda
  - defaults
dependencies:
  - python
  - jupyterlab
  - pip
  - tini
  - plotly
  - pip:
    - solo-sc
    - scrublet
    - kb-python
    - cellxgene
    - anndata
    - scanpy
    - scvi-tools
    - scanorama
    - bbknn
    - wot
