name: genomics
'on':
  push:
    branches: master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: Build and Push Bioc
        uses: docker/build-push-action@v2
        with:
          repository: shmohammadi86/genomics
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./mro-bioc
          file: ./mro-bioc/Dockerfile
          push: true
          build-args: |
            PARENT_DOCKER=shmohammadi86/genomics:mro
          tags: |
            shmohammadi86/genomics:mro-bioc
