name: ci
'on':
  push:
    branches: master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: '${{ secrets.AWS_REGISTRY_URL }}'
          username: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          password: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      - name: Build and push Single-cell
        uses: docker/build-push-action@v2
        with:
          context: ./singlecell
          file: ./singlecell/Dockerfile
          push: true
          build-args: |
            PARENT_DOCKER=shmohammadi86/genomics:mro-bioc-extra
          tags: |
            shmohammadi86/genomics:single-cell
            ${{ secrets.AWS_REGISTRY_URL }}/genomics:latest
