name: build images

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-pull images
        run: |
          docker pull ubuntu:20.04
      - name: List images
        run: |
          docker images
  
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Build MRO
        uses: actions/mro@master
        with: 
          PARENT_DOCKER: 'ubuntu:20.04'
