name: build images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-pull images
        run: |
          docker pull ubuntu:20.04
      - name: List images
        run: |
          docker images
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['mro']
    
    steps:
      - uses: actions/{{ matrix.version }}@master
      - name: Build image
        run: |
          docker build --tag genomics:${{ matrix.version }} ./${{ matrix.version }}
      - name: Run image
        run: |
          docker run -i --rm genomics:${{ matrix.version }} R -q -e 'sessionInfo(); print(paste("test:",1+41));' > run.log
          cat run.log
          
